name: Build and Push EasyConnect CLI Image
description: Build and push the amd64 and arm64 EasyConnect CLI image
inputs:
  registry_username:
    description: "Username for image registry"
    required: true
  registry_password:
    description: "Password for image registry"
    required: true
  ec_image_name:
    description: 'Name of the EasyConnect CLI image to push'
    required: true
    default: 'saitetimedout/docker-easyconnect'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Build and push EasyConnect CLI image
      shell: bash
      run: |
        branch="$(git branch --show-current)"
        case "$branch" in
          '' | master) tag=cli ;;
          develop) tag=dev-cli ;;
          *) tag="$branch-cli" ;;
        esac

        image="${{ inputs.ec_image_name }}:$tag"

        sudo apt-get update
        sudo apt-get -y install binfmt-support qemu-user-static

        for arch in arm64 amd64; do
          docker buildx build --build-arg BUILD_ENV=actions --platform "linux/$arch" \
            --load -t saitetimedout/docker-easyconnect:build -f Dockerfile.build .
          docker buildx build --build-arg BUILD_ENV=actions --build-arg EC_HOST=amd64 \
            --platform "linux/$arch" --load -t "$image-$arch" -f Dockerfile.cli .
          docker push "$image-$arch"
        done

        docker manifest create "$image" "$image-arm64" "$image-amd64"
        docker manifest push "$image"
